server:
  port: 9076
spring:
  application:
    name: Account-Service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Sushant#07
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true